---
title: Ben Ward
url: https://benward.uk
shortdomain: https://bnwrd.me
github_slug: BenWard/benward-web
git_base: 'jekyll'
author:
  name: Ben Ward
  url: https://benward.uk
  twitter: benward
layout: base
permalink: /:categories/:title.html
lsi: false
multiviews: true
markdown: rdiscount
exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile', 'import']
dateformat: "%b %e %Y, %k:%M (%z)"
timeformat: "%k:%M (%z)"
archive_month_index: archive_month.html
archive_year_index: archive_year.html
